export const COMMON_TOOLS = Object.freeze([
    'graph_stats', 'get_node', 'get_neighbors', 'query_graph', 'god_nodes',
    'shortest_path', 'get_dependents', 'change_impact', 'git_history',
    'verified_change', 'trace_api_contract', 'get_community', 'search_code',
    'read_source', 'inspect_symbol', 'context_bundle', 'find_duplicates',
    'find_dead_code', 'run_audit', 'coverage_map', 'hot_path_review',
    'list_communities', 'module_map', 'list_endpoints', 'trace_endpoint',
    'rebuild_graph', 'graph_diff', 'get_architecture_contract', 'prepare_change',
    'verify_architecture', 'explain_architecture_violation',
    'propose_architecture_exception', 'open_repo', 'list_known_repos',
])

export const PILOT_TOOLS = new Set([
    'graph_stats', 'get_node', 'get_neighbors', 'query_graph', 'god_nodes',
    'get_dependents', 'search_code', 'read_source', 'find_dead_code',
    'run_audit', 'module_map', 'list_endpoints',
])

export const CONTRACTS = Object.freeze({
    graph_stats: 'inventory+freshness',
    get_node: 'identity-resolution',
    get_neighbors: 'bounded-direct-relationships',
    query_graph: 'bounded-retrieval',
    god_nodes: 'ranked-connectivity-evidence',
    shortest_path: 'reachability-evidence',
    get_dependents: 'bounded-impact-evidence',
    change_impact: 'verdict+precision+coverage-boundary',
    git_history: 'bounded-history-evidence',
    verified_change: 'verdict+completeness-matrix',
    trace_api_contract: 'transport-verdict+static/runtime-completeness',
    get_community: 'community-inventory',
    search_code: 'bounded-source-matches',
    read_source: 'bounded-source-window',
    inspect_symbol: 'symbol-evidence+precision',
    context_bundle: 'bounded-context-evidence',
    find_duplicates: 'review-queue+confidence',
    find_dead_code: 'review-queue+confidence+no-auto-delete',
    run_audit: 'health-verdict+capability-matrix',
    coverage_map: 'measured-vs-static-completeness',
    hot_path_review: 'ranked-static-review-not-profiler',
    list_communities: 'community-inventory',
    module_map: 'module-inventory',
    list_endpoints: 'endpoint-inventory+confidence',
    trace_endpoint: 'route-resolution+bounded-call-evidence',
    rebuild_graph: 'structural-delta+freshness',
    graph_diff: 'structural-delta+baseline-completeness',
    get_architecture_contract: 'contract-state+no-implicit-approval',
    prepare_change: 'selected-rules+scope',
    verify_architecture: 'verdict+ratchet',
    explain_architecture_violation: 'fingerprint-resolution',
    propose_architecture_exception: 'proposal-only+no-mutation',
    open_repo: 'retarget-result',
    list_known_repos: 'registry-inventory',
})
